name: Build & Publish Image to GCR

on:
  push:
    branches:
    - master

env:
  #PROJECT_ID:   hackathon-297608
  PROJECT_ID:   zpm-package-manager
  GCR_LOCATION: eu.gcr.io
  REGION:       europe-west2
  #IMAGE_NAME:   ${{ github.repository }}
  IMAGE_NAME:   covid-19
  SERVICE:      covid-19
  GITHUB_SHA:   ${{ github.sha }}

jobs:
  deploy-cloud-run:
    name: Deploy to Cloud Run
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
 
    - name: Setup Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        version: '290.0.1'
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}

    - name: Authorize Docker push
      run: gcloud auth configure-docker

    - name: Build and Push Container
      run: |-
        docker build -t ${GCR_LOCATION}/${PROJECT_ID}/${IMAGE_NAME}:${GITHUB_SHA} .
        docker push ${GCR_LOCATION}/${PROJECT_ID}/${IMAGE_NAME}:${GITHUB_SHA}
        
    - name: Deploy to Cloud Run
      id: deploy
      uses: google-github-actions/deploy-cloudrun@v0.2.0
      with:
        service: ${{ env.SERVICE }}
        image: ${GCR_LOCATION}/${PROJECT_ID}/${IMAGE_NAME}:${GITHUB_SHA}
        region: ${{ env.REGION }}

    - name: Show Output
      run: echo ${{ steps.deploy.outputs.url }}

#  gcloud-install-build-push-GCR:
#    name: Add gcloud, Build & Publish
#    runs-on: ubuntu-18.04
#    steps:
#    - name: Checkout
#      uses: actions/checkout@v2
#
#    - name: Setup gcloud cli
#      uses: google-github-actions/setup-gcloud@v0.2.0
#      with:
#        version: '290.0.1'
#        service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
#
#    - name: Build & Publish
#      run: |
#        gcloud auth configure-docker
#        export TAG=${GCR_LOCATION}/${PROJECT_ID}/$(echo ${IMAGE_NAME,,} | tr '/' '-'):${GITHUB_SHA}
#        docker build --tag ${TAG} .
#        docker push ${TAG}
