name: Build & Publish Image to GCR

on:
  push:
    branches:
    - master

env:
  PROJECT_ID:   hackathon-297608
  GCR_LOCATION: eu.gcr.io
  IMAGE_NAME:   ${{ github.repository }}
  GITHUB_SHA:   ${{ github.sha }}

jobs:
  gcloud-install-build-push-GCR:
    name: Add gcloud, Build & Publish
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup gcloud cli
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        version: '290.0.1'
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}

    - name: Build & Publish
      run: |
        gcloud auth configure-docker
        export TAG=${GCR_LOCATION}/${PROJECT_ID}/$(echo ${IMAGE_NAME,,} | tr '/' '-'):${GITHUB_SHA}
        #docker build --tag ${TAG} .
        #docker push ${TAG}
        gcloud builds submit --tag ${TAG}
